# Created: 2026-01-09
import os
from datetime import datetime
from typing import Dict
from loguru import logger

class ReportGenerator:
    """
    Generates institutional-grade performance and risk reports.
    Note: In a production environment, this would use reportlab or similar for PDF.
    For this sprint, we generate a structured Markdown/Text report that can be converted.
    """
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_vault_report(self, vault_address: str, risk_profile: Dict, performance_data: Dict, stats: Dict = None):
        """
        Generates a comprehensive report for a specific vault.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
        filename = f"Kerne_Report_{vault_address[:8]}_{timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)
        
        stats = stats or {}
        
        report_content = f"""# Kerne Institutional Risk & Performance Report
**Vault:** `{vault_address}`
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 1. Executive Summary
The vault is currently operating within all risk parameters. The health score is **{risk_profile.health_score:.2f}/100**.

## 2. Risk Metrics
- **Net Delta:** {risk_profile.net_delta:.4f} (Target: 0.0000)
- **On-chain Liquidation Distance:** {risk_profile.liquidation_distance_onchain:.2%}
- **CEX Liquidation Distance:** {risk_profile.liquidation_distance_cex:.2%}
- **Gamma Exposure:** {risk_profile.gamma_exposure:.4f}

## 3. Performance Attribution
- **Current APY:** {performance_data['apy']:.2%}
- **Yield Sources:**
    - Funding Revenue: {performance_data['attribution']['funding_revenue']:.1%}
    - Basis Trading: {performance_data['attribution']['basis_trading']:.1%}
    - Staking Rewards: {performance_data['attribution']['staking_rewards']:.1%}

## 4. Execution Quality (Last 24h)
- **Average Slippage:** {stats.get('avg_slippage', 0.0):.4%}
- **Total Funding Captured:** {stats.get('total_funding', 0.0):.4f}
- **Max Drawdown:** {stats.get('max_drawdown', 0.0):.2%}
- **Sharpe Ratio:** {stats.get('sharpe_ratio', 0.0):.2f}

## 5. Compliance & Security
- **Audit Status:** Verified
- **Multi-sig Control:** Active
- **Emergency Unwind:** Ready
- **KYC/AML Hook:** Active (KerneComplianceHook)

---
*Generated by Kerne Sentinel Analytics Engine*
"""
        with open(filepath, "w") as f:
            f.write(report_content)
            
        logger.info(f"Generated report: {filepath}")
        return filepath
